---
server:
  proxied: true

pages:
  - name: Homelab
    columns:
      - size: full
        widgets:
          - type: monitor
            title: Media
            cache: 1m
            sites:
              - title: Calibre-Web-Automated
                url: https://cwa.nasenov.dev
                icon: di:calibre-web.svg
              - title: Audiobookshelf
                url: https://audiobookshelf.nasenov.dev
                icon: di:audiobookshelf.svg
              - title: Actual
                url: https://actual.nasenov.dev
                icon: di:actual-budget.svg
              - title: Fusion
                url: https://feeds.nasenov.dev
                icon: si:rss
              - title: Jellyfin
                url: https://jellyfin.nasenov.dev
                icon: di:jellyfin.svg
              - title: Jellyseerr
                url: https://jellyseerr.nasenov.dev
                icon: di:jellyseerr.svg
              - title: Radarr
                url: https://radarr.nasenov.dev
                icon: di:radarr.svg
              - title: Sonarr
                url: https://sonarr.nasenov.dev
                icon: di:sonarr.svg
              - title: Bazarr
                url: https://bazarr.nasenov.dev
                icon: di:bazarr.svg
              - title: Prowlarr
                url: https://prowlarr.nasenov.dev
                icon: di:prowlarr.svg
              - title: Qbittorrent
                url: https://qbittorrent.nasenov.dev
                icon: di:qbittorrent.svg
              - title: Autobrr
                url: https://autobrr.nasenov.dev
                icon: di:autobrr.svg
              - title: Qui
                url: https://qui.nasenov.dev
                icon: di:autobrr.svg
              - title: Thelounge
                url: https://thelounge.nasenov.dev
                icon: di:thelounge.svg

          - type: monitor
            title: Infrastructure
            cache: 1m
            sites:
              - title: Proxmox
                url: https://pve.nasenov.dev:8006
                icon: di:proxmox.svg
              - title: Truenas
                url: https://truenas.nasenov.dev
                icon: di:truenas.svg
              - title: Rook
                url: https://rook.nasenov.dev
                icon: di:rook.svg
              - title: Pi-hole
                url: http://192.168.0.53/admin
                icon: di:pi-hole.svg

          - type: monitor
            title: Monitoring
            cache: 1m
            sites:
              - title: Grafana
                url: https://grafana.nasenov.dev
                icon: di:grafana.svg
              - title: Prometheus
                url: https://prometheus.nasenov.dev
                icon: di:prometheus.svg
              - title: Alertmanager
                url: https://alertmanager.nasenov.dev
                icon: di:alertmanager.svg
              - title: Hubble
                url: https://hubble.nasenov.dev
                icon: di:cilium.svg
              - title: Alloy
                url: https://alloy.nasenov.dev
                icon: di:alloy.svg
              - title: Gatus
                url: https://gatus.nasenov.dev
                icon: di:gatus.svg

          - type: monitor
            title: Automation
            cache: 1m
            sites:
              - title: Home-assistant
                url: https://home-assistant.nasenov.dev
                icon: di:home-assistant.svg
              - title: Zigbee2mqtt
                url: https://zigbee.nasenov.dev
                icon: di:zigbee2mqtt.svg
              - title: n8n
                url: https://n8n.nasenov.dev
                icon: di:n8n.svg
  - name: Markets
    columns:
      - size: small
        widgets:
          - type: markets
            title: Crypto
            chart-link-template: https://www.tradingview.com/chart/?symbol={SYMBOL}
            markets:
              - symbol: BTC-USD
                name: Bitcoin
              - symbol: ETH-USD
                name: Ethereum

          - type: markets
            title: Stocks
            chart-link-template: https://www.tradingview.com/chart/?symbol={SYMBOL}
            sort-by: absolute-change
            markets:
              - symbol: AVGO
                name: Broadcom

      - size: full
        widgets:
          - type: videos
            style: vertical-list
            channels:
              - UCRvqjQPSeaWn-uEx-w0XOIg # Benjamin Cowen

          - type: group
            widgets:
              - type: reddit
                show-thumbnails: true
                subreddit: crypto
