---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin-password
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        GF_SECURITY_ADMIN_PASSWORD: "{{ .GF_SECURITY_ADMIN_PASSWORD }}"
  data:
    - secretKey: GF_SECURITY_ADMIN_PASSWORD
      remoteRef:
        key: 0a377bf4-c992-4a18-b33c-b3a30148c9d4
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-configuration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets-store
  target:
    template:
      data:
        GRAFANA_DATABASE_HOST: "{{ .pgbouncer_host }}:{{ .pgbouncer_port }}"
        GRAFANA_DATABASE_NAME: "{{ .dbname }}"
        GRAFANA_DATABASE_USER: "{{ .user }}"
        GRAFANA_DATABASE_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-grafana
      rewrite:
        - regexp:
            source: "-"
            target: "_"
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-postgres-datasource-configuration
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: postgres-secrets-store
  target:
    template:
      data:
        POSTGRES_DATASOURCE_URL: "{{ .pgbouncer_host }}:{{ .pgbouncer_port }}"
        POSTGRES_DATASOURCE_DATABASE: "{{ .dbname }}"
        POSTGRES_DATASOURCE_USER: "{{ .user }}"
        POSTGRES_DATASOURCE_PASSWORD: "{{ .password }}"
  dataFrom:
    - extract:
        key: postgres-pguser-fitness
      rewrite:
        - regexp:
            source: "-"
            target: "_"
