---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  deployment:
    spec:
      replicas: 2

      template:
        spec:
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password
                      key: GF_SECURITY_ADMIN_PASSWORD
              envFrom:
                - secretRef:
                    name: grafana-postgres-configuration

  config:
    database:
      type: postgres
      host: ${GRAFANA_DATABASE_HOST}
      name: ${GRAFANA_DATABASE_NAME}
      user: ${GRAFANA_DATABASE_USER}
      password: ${GRAFANA_DATABASE_PASSWORD}
      max_open_conn: "4"
      ssl_mode: require
    server:
      root_url: https://grafana.nasenov.dev
