---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/grafana.integreatly.org/grafana_v1beta1.json
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana
  labels:
    grafana.internal/instance: grafana
spec:
  deployment:
    spec:
      replicas: 2

      template:
        spec:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      grafana.internal/instance: grafana
          containers:
            - name: grafana
              env:
                - name: GF_SECURITY_ADMIN_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: grafana-admin-password
                      key: GF_SECURITY_ADMIN_PASSWORD
              envFrom:
                - secretRef:
                    name: grafana-postgres-configuration

  config:
    analytics:
      check_for_updates: "false"
      check_for_plugin_updates: "false"
      feedback_links_enabled: "false"
      reporting_enabled: "false"
    news:
      news_feed_enabled: "false"
    plugins:
      plugin_admin_enabled: "false"
    database:
      type: postgres
      host: ${GRAFANA_DATABASE_HOST}
      name: ${GRAFANA_DATABASE_NAME}
      user: ${GRAFANA_DATABASE_USER}
      password: ${GRAFANA_DATABASE_PASSWORD}
      max_open_conn: "4"
      ssl_mode: require
    server:
      enable_gzip: "true"
      root_url: https://grafana.nasenov.dev
