---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: nasenov-dev
spec:
  secretName: nasenov-dev-tls
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
  commonName: nasenov.dev
  dnsNames:
    - nasenov.dev
    - "*.nasenov.dev"
