---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-addons
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 10m0s
  dependsOn:
    - name: external-secrets-stores
    - name: prometheus-operator-crds
  path: ./kubernetes/apps/flux-system/addons/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
