---
apiVersion: v1alpha1
kind: HostnameConfig
hostname: k8s-3
auto: off
---
apiVersion: v1alpha1
kind: EthernetConfig
name: enp0s31f6
features:
  tx-tcp-segmentation: false
  tx-generic-segmentation: false
