---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: crunchy-postgres
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secrets-manager
  target:
    template:
      data:
        s3.conf: |
          [global]
          repo1-s3-key={{ .POSTGRESQL_GARAGE_ACCESS_KEY }}
          repo1-s3-key-secret={{ .POSTGRESQL_GARAGE_ACCESS_KEY_SECRET }}
          repo1-cipher-pass={{ .POSTGRESQL_BACKUP_ENCRYPTION_CIPHER_PASS }}
          repo2-s3-key={{ .POSTGRESQL_R2_ACCESS_KEY }}
          repo2-s3-key-secret={{ .POSTGRESQL_R2_ACCESS_KEY_SECRET }}
          repo2-cipher-pass={{ .POSTGRESQL_BACKUP_ENCRYPTION_CIPHER_PASS }}
  data:
    - secretKey: POSTGRESQL_GARAGE_ACCESS_KEY
      remoteRef:
        key: 43f2d5e8-52f6-4aa5-9776-b39d00ec1865
    - secretKey: POSTGRESQL_GARAGE_ACCESS_KEY_SECRET
      remoteRef:
        key: 3f19d6de-bce5-4134-891a-b39d00ec38d0
    - secretKey: POSTGRESQL_BACKUP_ENCRYPTION_CIPHER_PASS
      remoteRef:
        key: 4e4fa1a8-1f23-484a-84a0-b2b400c22ccd
    - secretKey: POSTGRESQL_R2_ACCESS_KEY
      remoteRef:
        key: 11c42bba-be43-44c4-883b-b2b400f3c72b
    - secretKey: POSTGRESQL_R2_ACCESS_KEY_SECRET
      remoteRef:
        key: 4c951d05-5b0d-41a6-b54c-b2b400f3edc9
