---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-import
spec:
  interval: 1h
  targetNamespace: networking
  dependsOn:
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/networking/certificates/import
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: certificates-export
spec:
  interval: 1h
  targetNamespace: networking
  dependsOn:
    - name: certificates-import
    - name: cert-manager-issuers
      namespace: cert-manager
    - name: external-secrets-stores
      namespace: external-secrets
  path: ./kubernetes/apps/networking/certificates/export
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
