metadata_dir = "/var/lib/garage/meta"
data_dir = "/var/lib/garage/data"
db_engine = "sqlite"

replication_factor = 1

rpc_bind_addr = "[::]:3901"

[s3_api]
api_bind_addr = "[::]:3900"
s3_region = "us-east-1"
root_domain = "s3.nasenov.dev"

[s3_web]
bind_addr = "[::]:3902"
root_domain = "garage.nasenov.dev"

[admin]
api_bind_addr = "[::]:3903"
